atlocal: Fix setting HAVE_PYTEST on unexpected errors.
If the python script throws an unexpected exception, the HAVE_PYTEST
variable remains undefined.  If at the same time dependencies are not
actually present, pytest tests will fail instead of being skipped.

Define the variable to 'no' on unexpected failures to skip the tests
when dependencies cannot be verified.

The issue can be reproduced on systems with python 3.12+ in case the
deprecated 'pkg_resources' module is not available.

Fixes: 445dceb88461 ("python: Introduce unit tests.")
Acked-by: Eelco Chaudron <echaudro@redhat.com>
Signed-off-by: Ilya Maximets <i.maximets@ovn.org>

diff --git a/tests/atlocal.in b/tests/atlocal.in
--- a/tests/atlocal.in
+++ b/tests/atlocal.in
@@ -252,5 +252,6 @@ with pathlib.Path(os.path.join(os.getenv("REQUIREMENT_PATH"))).open() as reqs:
 case $? in
     0) HAVE_PYTEST=yes ;;
     2) HAVE_PYTEST=no ;;
-    *) echo "$0: unexpected error probing Python unit test requirements" >&2 ;;
+    *) HAVE_PYTEST=no
+       echo "$0: unexpected error probing Python unit test requirements" >&2 ;;
 esac
