dkms.conf.in: Install all kernel modules.
With the latest change of separating vports into their own modules,
we need to update the dkms.conf.in and make dkms install all vport
modules.  So, this commit modifies the debian/rules to read all
kernel module names and sets the dkms.conf correctly.

Signed-off-by: Alex Wang <alexw@nicira.com>

diff --git a/datapath/Makefile.am b/datapath/Makefile.am
--- a/datapath/Makefile.am
+++ b/datapath/Makefile.am
@@ -20,3 +20,12 @@ distfiles: Makefile
 	  sed -e "s|^$$srcdirstrip/||;t" \
 	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t" | sort -u > $@
 CLEANFILES = distfiles
+
+# Print name of all modules.
+print-build-modules:
+	@if test -z "$(build_modules)"; \
+	then \
+	   echo "Could not find any kernel module."; \
+	   exit 1; \
+	fi
+	@echo "$(build_modules)" | tr '_' '-';
