xenserver: Improve vif hotplug script for XenServer 5.7.
The vif hotplug script has the following changes:

      * Read extra vif details from xenstore instead of using XenAPI.
        This reduces unnecessary traffic on the pool master and is good
        for scalability. This change makes the dump-vif-details script
        redundant.
      * Manage network tap devices (emulated network devices created by
        qemu) via the hotplug script. Replaces usage
        of /etc/xen/qemu-ifup (which is removed in XenServer 5.7). This
        is necessary in order to receive tap deletion a well as creation
        events. Modified /etc/udev/rules/xen-backend.rules also
        attached.

These changes are not compatible with XenServer 5.0 since they require
changes to xapi which were made in the 5.7 branch. The first change
definitely requires xapi support while the second requires a kernel with
correctly working hotplug events on tap devices. I haven't confirmed but
I believe the 2.6.18 kernel used in XenServer 5.0 does not (old kernels
do not generate a hotplug even for a tap device until it is brought up).
The 2.6.27 kernel used in XenServer 5.7 does have usable hotplug events
on tap devices.

(Ian Campbell made all the changes to the vif scripts and xen-backend.rules
files and wrote the above commit log.  Ben Pfaff updated the rest of the
file to integrate into the build.)

diff --git a/xenserver/etc_xensource_scripts_vif b/xenserver/etc_xensource_scripts_vif
--- a/xenserver/etc_xensource_scripts_vif
+++ b/xenserver/etc_xensource_scripts_vif
@@ -12,26 +12,15 @@
 # Keep other-config/ keys in sync with device.ml:vif_udev_keys
 
 cfg_mod="/usr/bin/ovs-cfg-mod"
-dump_vif_details="/usr/share/vswitch/scripts/dump-vif-details"
 service="/sbin/service"
-
-TYPE=`echo ${XENBUS_PATH} | cut -f 2 -d '/'`
-DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
-DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`
-
-XAPI=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}
-HOTPLUG=/xapi/${DOMID}/hotplug/${TYPE}/${DEVID}
-PRIVATE=/xapi/${DOMID}/private/${TYPE}/${DEVID}
-BRCTL=/usr/sbin/brctl
-IP=/sbin/ip
-
+IP="/sbin/ip"
 
 handle_promiscuous()
 {
-    local arg=$(xenstore-read "${PRIVATE}/other-config/promiscuous")
+    local arg=$(xenstore-read "${PRIVATE}/other-config/promiscuous" 2>/dev/null)
     if [ $? -eq 0 -a -n "${arg}" ] ; then
         case "${arg}" in 
-            true|on) logger -t script-vif "${vif}: Promiscuous ports are not supported via vSwitch." ;;
+            true|on) logger -t script-vif "${dev}: Promiscuous ports are not supported via vSwitch." ;;
             *) ;;
         esac
     fi
@@ -40,22 +29,50 @@ handle_promiscuous()
 handle_ethtool()
 {
     local opt=$1
-    local arg=$(xenstore-read "${PRIVATE}/other-config/ethtool-${opt}")
+    local arg=$(xenstore-read "${PRIVATE}/other-config/ethtool-${opt}" 2>/dev/null)
     if [ $? -eq 0 -a -n "${arg}" ] ; then
         case "${arg}" in
-            true|on)   /sbin/ethtool -K "${vif}" "${opt}" on ;;
-            false|off) /sbin/ethtool -K "${vif}" "${opt}" off ;;
-            *) logger -t scripts-vif "Unknown ethtool argument ${opt}=${arg} on ${vif}/${VIFUUID}" ;;
+            true|on)   /sbin/ethtool -K "${dev}" "${opt}" on ;;
+            false|off) /sbin/ethtool -K "${dev}" "${opt}" off ;;
+            *) logger -t scripts-vif "Unknown ethtool argument ${opt}=${arg} on ${dev}/${VIFUUID}" ;;
         esac
     fi
 }
 
 handle_mtu()
 {
-    local mtu=$(xenstore-read "${PRIVATE}/MTU")
+    local mtu=$(xenstore-read "${PRIVATE}/MTU" 2>/dev/null)
     if [ $? -eq 0 -a -n "${mtu}" ]; then
-	echo "${mtu}" > /sys/class/net/${vif}/mtu
+	echo "${mtu}" > /sys/class/net/${dev}/mtu
     fi
+}
+
+handle_vif_details()
+{
+    local vif_details=
+    local net_uuid=$(xenstore-read "${PRIVATE}/network-uuid" 2>/dev/null)
+    if [ -n "${net_uuid}" ] ; then
+	vif_details="$vif_details --add=port.${dev}.net-uuid=${net_uuid}"
+    fi
+
+    local address=$(xenstore-read "/local/domain/$DOMID/device/vif/$DEVID/mac" 2>/dev/null)
+    if [ -n "${address}" ] ; then
+	vif_details="$vif_details --add=port.${dev}.vif-mac=${address}"
+    fi
+
+    local vif_uuid=$(xenstore-read "${PRIVATE}/vif-uuid" 2>/dev/null)
+    if [ -n "${vif_uuid}" ] ; then
+	vif_details="$vif_details --add=port.${dev}.vif-uuid=${vif_uuid}"
+    fi
+
+    local vm=$(xenstore-read "/local/domain/$DOMID/vm" 2>/dev/null)
+    if [ $? -eq 0 -a -n "${vm}" ] ; then
+	local vm_uuid=$(xenstore-read "$vm/uuid" 2>/dev/null)
+    fi
+    if [ -n "${vm_uuid}" ] ; then
+	vif_details="$vif_details --add=port.${dev}.vm-uuid=${vm_uuid}"
+    fi
+    echo ${vif_details}
 }
 
 add_to_bridge()
@@ -63,73 +80,106 @@ add_to_bridge()
     local address=$(xenstore-read "${PRIVATE}/bridge-MAC")
     if [ $? -ne 0 -o -z "${address}" ]; then
 	logger -t scripts-vif "Failed to read ${PRIVATE}/bridge-MAC from xenstore"
+	exit 1
     fi
     local bridge=$(xenstore-read "${PRIVATE}/bridge")
     if [ $? -ne 0 -o -z "${bridge}" ]; then
 	logger -t scripts-vif "Failed to read ${PRIVATE}/bridge from xenstore"
+	exit 1
     fi
-    logger -t scripts-vif "Adding ${vif} to ${bridge} with address ${address}"
+    logger -t scripts-vif "Adding ${dev} to ${bridge} with address ${address}"
 
     vid=
     if [ -e "/var/lib/openvswitch/br-$bridge" ]; then
 	. "/var/lib/openvswitch/br-$bridge"
 	if [ -n "$VLAN_SLAVE" -a -n "$VLAN_VID" ]; then
 	    bridge=$VLAN_SLAVE
-	    vid="--add=vlan.$vif.tag=$VLAN_VID"
+	    vid="--add=vlan.${dev}.tag=$VLAN_VID"
 	fi
     fi
 
-    ${IP} link set "${vif}" down                        || logger -t scripts-vif "Failed to ip link set ${vif} down"
-    ${IP} link set "${vif}" arp off                     || logger -t scripts-vif "Failed to ip link set ${vif} arp off"
-    ${IP} link set "${vif}" multicast off               || logger -t scripts-vif "Failed to ip link set ${vif} multicast off"
-    ${IP} link set "${vif}" address "${address}"        || logger -t scripts-vif "Failed to ip link set ${vif} address ${address}"
-    ${IP} addr flush "${vif}"                           || logger -t scripts-vif "Failed to ip addr flush ${vif}"
-
-    local vif_details=$($dump_vif_details $DOMID $DEVID)
-    if [ $? -ne 0 -o -z "${vif_details}" ]; then
-	    logger -t scripts-vif "Failed to retrieve vif details for vswitch"
+    if [ "$type" = "vif" ] ; then
+	local vif_details=$(handle_vif_details)
     fi
 
+    ${IP} link set "${dev}" down                        || logger -t scripts-vif "Failed to ip link set ${dev} down"
+    ${IP} link set "${dev}" arp off                     || logger -t scripts-vif "Failed to ip link set ${dev} arp off"
+    ${IP} link set "${dev}" multicast off               || logger -t scripts-vif "Failed to ip link set ${dev} multicast off"
+    ${IP} link set "${dev}" address "${address}"        || logger -t scripts-vif "Failed to ip link set ${dev} address ${address}"
+    ${IP} addr flush "${dev}"                           || logger -t scripts-vif "Failed to ip addr flush ${dev}"
+
     $cfg_mod -F /etc/ovs-vswitchd.conf \
-        --del-match="bridge.*.port=$vif" \
-        --del-match="vlan.$vif.[!0-9]*" \
-        --del-match="port.$vif.[!0-9]*" \
-        --add="bridge.$bridge.port=$vif" \
+        --del-match="bridge.*.port=${dev}" \
+        --del-match="vlan.${dev}.[!0-9]*" \
+        --del-match="port.${dev}.[!0-9]*" \
+        --add="bridge.$bridge.port=${dev}" \
         $vid $vif_details -c 
     $service vswitch reload
 
-    ${IP} link set "${vif}" up                          || logger -t scripts-vif "Failed to ip link set ${vif} up"
+    ${IP} link set "${dev}" up                          || logger -t scripts-vif "Failed to ip link set ${dev} up"
 }
 
-echo Called as "$@" "$TYPE" "$DOMID" "$DEVID" | logger -t scripts-vif
+type=$2
+
+case ${type} in
+    vif)
+	DOMID=`echo ${XENBUS_PATH} | cut -f 3 -d '/'`
+	DEVID=`echo ${XENBUS_PATH} | cut -f 4 -d '/'`
+	dev=vif${DOMID}.${DEVID}
+	;;
+    tap)
+	dev=$INTERFACE
+	DOMID=`echo ${dev#tap} | cut -f 1 -d '.'`
+	DEVID=`echo ${dev#tap} | cut -f 2 -d '.'`
+	;;
+    *)  
+	logger -t scripts-vif "unknown interface type ${type}"
+	exit 1
+	;;
+esac
+
+XAPI=/xapi/${DOMID}/hotplug/vif/${DEVID}
+HOTPLUG=/xapi/${DOMID}/hotplug/vif/${DEVID}
+PRIVATE=/xapi/${DOMID}/private/vif/${DEVID}
+
+echo Called as "$@" "$DOMID" "$DEVID" | logger -t scripts-vif
 case "$1" in
 online)
-	handle_ethtool rx
-	handle_ethtool tx
-	handle_ethtool sg
-	handle_ethtool tso
-	handle_ethtool ufo
-	handle_ethtool gso
+	if [ "${type}" = "vif" ] ; then
+	    handle_ethtool rx
+	    handle_ethtool tx
+	    handle_ethtool sg
+	    handle_ethtool tso
+	    handle_ethtool ufo
+	    handle_ethtool gso
 
-	handle_mtu
-	add_to_bridge
-	handle_promiscuous
+	    handle_mtu
+	    add_to_bridge
+	    handle_promiscuous
 
-	xenstore-write "${HOTPLUG}/vif" "${vif}"
-	xenstore-write "${HOTPLUG}/hotplug" "online"
+	    xenstore-write "${HOTPLUG}/vif" "${dev}"
+	    xenstore-write "${HOTPLUG}/hotplug" "online"
 
-	# xs-xen.pq.hq:91e986b8e49f netback-wait-for-hotplug
-	xenstore-write "/local/domain/0/backend/vif/${DOMID}/${DEVID}/hotplug-status" "connected"
-
+	    # xs-xen.pq.hq:91e986b8e49f netback-wait-for-hotplug
+	    xenstore-write "/local/domain/0/backend/vif/${DOMID}/${DEVID}/hotplug-status" "connected"
+	fi
 	;;
+
+add)
+	if [ "${type}" = "tap" ] ; then
+	    add_to_bridge
+	fi
+	;;
+
 remove)
-	xenstore-rm "${HOTPLUG}/hotplug"
-	vif=vif${DOMID}.${DEVID}
-	logger -t scripts-vif "${vif} has been removed"
+	if [ "${type}" = "vif" ] ;then
+	    xenstore-rm "${HOTPLUG}/hotplug"
+	fi
+	logger -t scripts-vif "${dev} has been removed"
 	$cfg_mod -vANY:console:emer -F /etc/ovs-vswitchd.conf \
-	    --del-match="bridge.*.port=${vif}" \
-	    --del-match="vlan.${vif}.[!0-9]*" \
-	    --del-match="port.${vif}.[!0-9]*" -c
+	    --del-match="bridge.*.port=${dev}" \
+	    --del-match="vlan.${dev}.[!0-9]*" \
+	    --del-match="port.${dev}.[!0-9]*" -c
 	$service vswitch reload
 	;;
 esac
